name: AnimalQuest
version: '1.0-SNAPSHOT'
main: ca.pandaaa.animalquest.AnimalQuest
api-version: '1.21'

commands:
  animalquest:
    permission: animalquest.admin
    aliases: [aq]
  jobs:
    permission: animalquest.jobs
    description: Open the jobs GUI

permissions:
  animalquest.admin:
    description: Full admin access to AnimalQuest commands
  animalquest.jobs:
    description: Use the /jobs command to view job progress
    default: true
