name: AnimalQuest
version: '1.0-SNAPSHOT'
main: ca.pandaaa.animalquest.AnimalQuest
depend: [CustomMobs]
api-version: '1.21.11'

commands:
  animalquest:
    aliases: [aq]
    description: AnimalQuest Admin commands.
  menu:
    description: AnimalQuest Menu command.
  guild:
    description: AnimalQuest Guild commands.
  pay:
    description: AnimalQuest Pay command.
  aptitudes:
    aliases: [apt]
    description: AnimalQuest Aptitude command.
  mount:
    aliases: [mt]
    description: Spawns your mount.
  vanish:
    aliases: [v]
    description: Vanish.
  broadcast:
    aliases: [bc]
    description: Broadcast.
  staffchat:
    aliases: [sc]
    description: StaffChat.
  quests:
    description: Quest menu and commands.
  jobs:
    description: Jobs menu and commands.
  worldreset:
    aliases: [wr]
    description: World reset system commands.
