name: AnimalQuest
version: '1.0-SNAPSHOT'
main: ca.pandaaa.animalquest.AnimalQuest
api-version: '1.21'

commands:
  animalquest:
    permission: animalquest.admin
    aliases: [aq]
  aptitudes:
    aliases: [apt]
